const A='assets/';
const heroes=[
 {id:'kael',name:'Каэль Рейн',rarity:5,el:'Огонь',role:'Дуэлянт',img:'hero_5_fire.jpg',desc:'Наследник пламени, который слышит голос древнего дракона.'},
 {id:'lyra',name:'Лира Мелл',rarity:4,el:'Вода',role:'Лекарь',img:'hero_4_water.jpg'},
 {id:'bronn',name:'Бронна Вальд',rarity:4,el:'Земля',role:'Страж',img:'hero_4_earth.jpg'},
 {id:'soren',name:'Сорен Вейл',rarity:4,el:'Воздух',role:'Разведчик',img:'hero_4_air.jpg'},
 {id:'elia',name:'Элия Нокс',rarity:4,el:'Свет',role:'Оракул',img:'hero_4_light.jpg'}
];
const state=JSON.parse(localStorage.giare||'null')||{page:'map',crystals:1200,tickets:12,pity:0,high:0,cleared:0,owned:['kael','lyra','bronn','soren']};
const save=()=>localStorage.giare=JSON.stringify(state); const app=document.querySelector('#app');
function toast(t){const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function nav(){return `<header class="topbar"><div class="logo">GIARE<small>ARCANA ACADEMY</small></div><nav class="nav">${[['map','Карта'],['summon','Призыв'],['roster','Отряд'],['arena','Арена'],['academy','Академия']].map(x=>`<button class="${state.page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav><div class="resources"><div class="resource">✦ <b>${state.crystals}</b></div><div class="resource">◈ <b>${state.tickets}</b></div></div></header>`}
function card(h){return `<div class="card hero-card" style="--img:url('${A+h.img}')"><div class="card-body"><div class="stars">${'★'.repeat(h.rarity)}</div><h3>${h.name}</h3><span class="tag">${h.el} · ${h.role}</span></div></div>`}
function mapPage(){let unlocked=state.cleared+1;return `<main class="main"><div class="eyebrow">Глава 01 · Пролог</div><h1 class="hero-title">Путь <span>стихий</span></h1><p class="subtitle">Добро пожаловать в академию Астэрия. Пройди десять этажей первой главы, чтобы пробудить арену и раскрыть тайны небесного разлома.</p><div style="margin:25px 0"><button class="button" onclick="startFloor(${Math.min(unlocked,10)})">Продолжить путь →</button> <button class="button ghost" onclick="go('summon')">Открыть призыв</button></div><div class="content-grid"><section class="panel"><div class="section-head"><h2>Башня Астэрии</h2><span>${state.cleared}/10 этажей очищено</span></div><div class="floors">${Array.from({length:10},(_,i)=>`<button class="floor ${i<state.cleared?'done':''} ${i>unlocked-1?'locked':''}" ${i>unlocked-1?'disabled':''} onclick="startFloor(${i+1})">${i<state.cleared?'✓':i+1}</button>`).join('')}</div><div class="status" style="margin-top:18px"><div class="orb"></div><div><b>Следующая цель</b><br><span>Этаж ${Math.min(unlocked,10)} · Испытание стихий</span></div></div></section><section class="panel"><h3>Задания академии</h3><div class="mission"><span>Завершить этаж башни</span><b>${state.cleared}/10</b></div><div class="mission"><span>Призвать героя</span><b>0/1</b></div><div class="mission"><span>Собрать отряд</span><b>${state.owned.length}/4</b></div></section></div><div class="section-head"><h2>Твой отряд</h2><button class="button ghost" onclick="go('roster')">Управление отрядом</button></div><div class="cards">${state.owned.slice(0,4).map(id=>card(heroes.find(h=>h.id===id))).join('')}</div></main>`}
function summonPage(){return `<main class="main"><div class="summon-wrap"><div class="eyebrow">Единый баннер · Архив призыва</div><div class="summon-orb"></div><h1>Клятва рассвета</h1><p>Призывай героев академии и открой силу шести стихий.</p><div class="rates"><span>5★ <b>1.0%</b></span><span>4★ <b>9.0%</b></span><span>3★ <b>90.0%</b></span></div><div class="summon-actions"><button class="button ghost" onclick="pull(1)">Призыв ×1 <small>(1 ◈)</small></button><button class="button" onclick="pull(10)">Призыв ×10 <small>(10 ◈)</small></button></div><p class="small" style="margin-top:22px">Гарант 4★: ${10-state.pity} призывов · Гарант 5★: ${90-state.high} призывов</p></div></main>`}
function rosterPage(){return `<main class="main"><div class="eyebrow">Коллекция резонансов</div><h1 class="hero-title">Твой <span>отряд</span></h1><p class="subtitle">Герои, которых ты призвал. Три звезды — оружие и расходные материалы.</p><div class="cards">${state.owned.map(id=>card(heroes.find(h=>h.id===id))).join('')}</div><div class="panel" style="margin-top:20px"><h3>Резонанс стихий</h3><div class="bar"><i style="width:${state.owned.length/5*100}%"></i></div><p class="small">Собери пять героев, чтобы открыть бонус «Единство академии».</p></div></main>`}
function arenaPage(){if(state.cleared<10)return `<main class="main"><div class="panel locked-screen"><div class="lock">⌁</div><h1>Арена запечатана</h1><p class="subtitle" style="margin:15px auto">Пройди все 10 этажей главы 1, чтобы бросить вызов командам академии.</p><button class="button" onclick="go('map')">Вернуться к карте</button></div></main>`;return `<main class="main"><div class="eyebrow">Испытание команд</div><h1 class="hero-title">Арена <span>Эфира</span></h1><div class="arena"><div class="combatants"><div class="combatant"><div class="avatar" style="--img:url('${A+'hero_5_fire.jpg'}')"></div><b>Твой отряд</b><div class="small">Сила 4 280</div></div><div class="vs">VS</div><div class="combatant"><div class="avatar" style="--img:url('${A+'hero_4_earth.jpg'}')"></div><b>Стражи Зала</b><div class="small">Сила 4 100</div></div></div><div class="log">⚔ Пошаговый бой · Ручной режим доступен<br><span>Победа принесёт 120 кристаллов академии.</span></div><button class="button" style="margin-top:22px" onclick="toast('Бой начался! Выбери способность героя.')">Начать бой</button></div></main>`}
function academyPage(){return `<main class="main"><div class="eyebrow">Центр развития</div><h1 class="hero-title">Академия <span>Астэрия</span></h1><div class="content-grid"><div class="panel" style="background:linear-gradient(180deg,rgba(7,9,24,.2),rgba(7,9,24,.9)),url('assets/bg_library.jpg') center/cover;min-height:330px"><h3>Библиотека заклинаний</h3><p class="subtitle">Изучай способности, повышай уровень героев и открывай новые комбинации стихий.</p><button class="button ghost" onclick="toast('Раздел развития появится в следующем обновлении')">Исследовать</button></div><div class="panel"><h3>Печать академии</h3><p class="subtitle">Твой прогресс сохраняется автоматически в этом браузере.</p><div class="mission"><span>Уровень аккаунта</span><b>1</b></div><div class="mission"><span>Опыт</span><b>240/1000</b></div><div class="mission"><span>Открыто героев</span><b>${state.owned.length}/5</b></div><button class="button cyan" style="margin-top:18px" onclick="toast('Награда получена: 100 ✦');state.crystals+=100;save();render()">Забрать награду</button></div></div></main>`}
function render(){app.innerHTML=`<div class="app">${nav()}${state.page==='map'?mapPage():state.page==='summon'?summonPage():state.page==='roster'?rosterPage():state.page==='arena'?arenaPage():academyPage()}</div>`} function go(p){state.page=p;save();render();window.scrollTo(0,0)}
function pull(n){if(state.tickets<n){toast('Недостаточно билетов призыва');return}state.tickets-=n;let five=(state.high+n>=90)||Math.random()<.01;let four=!five&&(state.pity+n>=10||Math.random()<.09);let h=five?heroes[0]:four?heroes[1+Math.floor(Math.random()*4)]:null;state.pity=four||five?0:state.pity+n;state.high=five?0:state.high+n;if(h&&!state.owned.includes(h.id))state.owned.push(h.id);save();document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal"><div class="modal"><div class="eyebrow">Результат призыва</div>${h?`<div class="result" style="--img:url('${A+h.img}')"></div><h2>${h.name}</h2><p class="tag">${h.rarity}★ · ${h.el} · ${h.role}</p>`:`<div class="result" style="--img:url('${A+'bg_summon.jpg'}')"></div><h2>Оружие академии</h2><p class="tag">3★ · Материал усиления</p>`}<button class="button" style="margin-top:18px" onclick="document.querySelector('#modal').remove();render()">Продолжить</button></div></div>`)}
function startFloor(n){if(n>state.cleared+1){toast('Этот этаж пока запечатан');return}let win=confirm(`Этаж ${n}\n\nВойти в пошаговый бой?`);if(win){state.cleared=Math.max(state.cleared,n);state.crystals+=40;save();toast(`Этаж ${n} очищен · +40 кристаллов`);render()}}
render();
